name: Auto update go dependencies

on:
  schedule:
    # runs daily at 12:00 am
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  auto-update-go:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2
      with:
        persist-credentials: false
          
    - name: Go setup
      uses: actions/setup-go@v2
             
    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@main
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: "dependencies-autoupdate"
        update-command: "'go get -u && go run'"
        path: "'./test/go'"
        username: "romoh"
        organization: "romoh"
        
